name: Build and Commit (Non-Fork Pushes)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

permissions:
  contents: write

jobs:
  commit_and_push:
    runs-on: ubuntu-latest
    name: Build and commit changes
    # Skip for forks
    if: github.repository_owner == 'impresscms-dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run pack
        run: npm run pack

      - name: List files in dist directory
        run: ls -la dist/

      - name: Auto committing changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automatically built and updated'
          file_pattern: 'dist/*.*'
          commit_options: '--no-verify'
          push_options: '--force'

